'use client';
import { useState } from 'react';
import LocalToolLayout from '@/components/LocalToolLayout';
import { detectFileSignature, extensionMatches, fileExtension, type SignatureInfo } from '@/lib/file-signatures';

type Result = { info: SignatureInfo | null; matches: boolean | null; hex: string; extension: string };
export default function FileSignatureInspectorPage() {
  const [file, setFile] = useState<File | null>(null); const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState('');
  const inspect = async (next: File) => { setFile(next); setError(''); try { const bytes = new Uint8Array(await next.slice(0, 64).arrayBuffer()); const info = detectFileSignature(bytes); setResult({ info, matches: extensionMatches(info, next.name), extension: fileExtension(next.name), hex: Array.from(bytes).map(value => value.toString(16).padStart(2,'0')).join(' ').toUpperCase() }); } catch (err) { setResult(null); setError((err as Error).message); } };
  return <LocalToolLayout title='File Type & Signature Inspector' description='Inspect the magic bytes at the start of a file instead of trusting only its filename. The file stays on your device.'><section className='mx-auto max-w-3xl rounded-xl bg-white p-6 shadow'><input type='file' onChange={event => event.target.files?.[0] && void inspect(event.target.files[0])} className='w-full rounded border p-3'/>{file && <p className='mt-3 text-sm text-slate-600'>{file.name} · {(file.size / 1024).toFixed(1)} KB</p>}{error && <p className='mt-4 text-red-600'>{error}</p>}{result && <div className='mt-6 space-y-4'><div className='rounded-lg bg-slate-50 p-4'><p className='text-sm text-slate-500'>Detected signature</p><p className='text-xl font-semibold text-slate-800'>{result.info?.name ?? 'Unknown / not in local signature table'}</p>{result.info && <p className='mt-1 font-mono text-sm'>{result.info.mime}</p>}</div>{result.matches !== null && <div className={`rounded-lg p-4 ${result.matches ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-900'}`}>{result.matches ? `The .${result.extension} extension is consistent with this signature.` : `The .${result.extension} extension does not match the detected signature.`}{result.info?.container && <p className='mt-2 text-sm'>This is a container format, so the signature alone cannot identify the exact document/media subtype.</p>}</div>}<div><p className='mb-2 text-sm font-semibold'>First bytes</p><pre className='overflow-auto rounded bg-slate-950 p-4 text-xs text-slate-100'>{result.hex}</pre></div></div>}</section></LocalToolLayout>;
}
