'use client';
import { useMemo, useState } from 'react';
import LocalToolLayout from '@/components/LocalToolLayout';
const LOWER='abcdefghijkmnopqrstuvwxyz'; const UPPER='ABCDEFGHJKLMNPQRSTUVWXYZ'; const DIGITS='23456789'; const SYMBOLS='!@#$%^&*()-_=+[]{}:,.?';
function securePick(chars:string){const max=Math.floor(256/chars.length)*chars.length;const a=new Uint8Array(1);do crypto.getRandomValues(a);while(a[0]>=max);return chars[a[0]%chars.length]}
function makePassword(length:number,sets:string[]){const pool=sets.join('');if(!pool)return '';let out=sets.map(securePick).join('');while(out.length<length)out+=securePick(pool);return out.split('').map((c,i,a)=>{const j=Math.floor(Math.random()*a.length);[a[i],a[j]]=[a[j],a[i]];return a[i]}).join('').slice(0,length)}
const WORDS=['amber','apple','atlas','bamboo','beacon','blue','cedar','cloud','cobalt','comet','coral','delta','ember','falcon','fern','forest','galaxy','garden','harbor','indigo','jungle','lantern','lemon','lotus','maple','meadow','meteor','mint','nebula','ocean','olive','orbit','pearl','pine','pixel','quartz','raven','river','saffron','solar','spruce','stone','sunset','tiger','violet','willow','winter','zenith'];
function passphrase(n:number){const a=new Uint32Array(n);crypto.getRandomValues(a);return [...a].map(v=>WORDS[v%WORDS.length]).join('-')}
export default function PasswordGeneratorPage(){const [length,setLength]=useState(20);const [upper,setUpper]=useState(true);const [digits,setDigits]=useState(true);const [symbols,setSymbols]=useState(true);const [nonce,setNonce]=useState(0);const [words,setWords]=useState(5);const password=useMemo(()=>makePassword(length,[LOWER,upper?UPPER:'',digits?DIGITS:'',symbols?SYMBOLS:''].filter(Boolean)),[length,upper,digits,symbols,nonce]);const phrase=useMemo(()=>passphrase(words),[words,nonce]);return <LocalToolLayout title='Password & Passphrase Generator' description='Generate secrets locally with cryptographically secure randomness. Nothing is stored or transmitted.'><section className='mx-auto max-w-3xl space-y-6 rounded-xl bg-white p-6 shadow'><div><div className='flex gap-2'><input readOnly value={password} className='min-w-0 flex-1 rounded border p-3 font-mono'/><button onClick={()=>navigator.clipboard.writeText(password)} className='rounded bg-slate-800 px-4 text-white'>Copy</button></div><label className='mt-4 block'>Length: {length}<input type='range' min='12' max='64' value={length} onChange={e=>setLength(+e.target.value)} className='w-full'/></label><div className='mt-3 flex flex-wrap gap-4'>{[['Uppercase',upper,setUpper],['Numbers',digits,setDigits],['Symbols',symbols,setSymbols]].map(([label,val,setter])=><label key={label as string} className='flex gap-2'><input type='checkbox' checked={val as boolean} onChange={e=>(setter as (v:boolean)=>void)(e.target.checked)}/>{label as string}</label>)}</div></div><div className='border-t pt-6'><div className='flex gap-2'><input readOnly value={phrase} className='min-w-0 flex-1 rounded border p-3 font-mono'/><button onClick={()=>navigator.clipboard.writeText(phrase)} className='rounded bg-slate-800 px-4 text-white'>Copy</button></div><label className='mt-4 block'>Words: {words}<input type='range' min='4' max='10' value={words} onChange={e=>setWords(+e.target.value)} className='w-full'/></label></div><button onClick={()=>setNonce(n=>n+1)} className='rounded bg-sky-600 px-5 py-2 text-white'>Generate new</button></section></LocalToolLayout>}
