'use client';
import { useMemo, useState } from 'react';
import LocalToolLayout from '@/components/LocalToolLayout';
const LOWER='abcdefghijkmnopqrstuvwxyz'; const UPPER='ABCDEFGHJKLMNPQRSTUVWXYZ'; const DIGITS='23456789'; const SYMBOLS='!@#$%^&*()-_=+[]{}:,.?';
function secureInt(max:number){if(max<=0)return 0;const limit=Math.floor(0x100000000/max)*max;const a=new Uint32Array(1);do crypto.getRandomValues(a);while(a[0]>=limit);return a[0]%max}
function securePick(chars:string){return chars[secureInt(chars.length)]}
function secureShuffle(chars:string){const a=[...chars];for(let i=a.length-1;i>0;i--){const j=secureInt(i+1);[a[i],a[j]]=[a[j],a[i]]}return a.join('')}
function makePassword(length:number,sets:string[]){const usable=sets.filter(Boolean);const pool=usable.join('');if(!pool)return '';let out=usable.map(securePick).join('');while(out.length<length)out+=securePick(pool);return secureShuffle(out).slice(0,length)}
const WORDS=['amber','apple','atlas','bamboo','beacon','blue','cedar','cloud','cobalt','comet','coral','delta','ember','falcon','fern','forest','galaxy','garden','harbor','indigo','jungle','lantern','lemon','lotus','maple','meadow','meteor','mint','nebula','ocean','olive','orbit','pearl','pine','pixel','quartz','raven','river','saffron','solar','spruce','stone','sunset','tiger','violet','willow','winter','zenith'];
function passphrase(n:number){return Array.from({length:n},()=>WORDS[secureInt(WORDS.length)]).join('-')}
export default function PasswordGeneratorPage(){const [length,setLength]=useState(20);const [upper,setUpper]=useState(true);const [digits,setDigits]=useState(true);const [symbols,setSymbols]=useState(true);const [nonce,setNonce]=useState(0);const [words,setWords]=useState(5);const password=useMemo(()=>{void nonce;return makePassword(length,[LOWER,upper?UPPER:'',digits?DIGITS:'',symbols?SYMBOLS:''])},[length,upper,digits,symbols,nonce]);const phrase=useMemo(()=>{void nonce;return passphrase(words)},[words,nonce]);return <LocalToolLayout title='Password & Passphrase Generator' description='Generate secrets locally with cryptographically secure browser randomness. Nothing is stored or transmitted.'><section className='mx-auto max-w-3xl space-y-6 rounded-xl bg-white p-6 shadow'><div><div className='flex gap-2'><input readOnly value={password} className='min-w-0 flex-1 rounded border p-3 font-mono'/><button onClick={()=>navigator.clipboard.writeText(password)} className='rounded bg-slate-800 px-4 text-white'>Copy</button></div><label className='mt-4 block'>Length: {length}<input type='range' min='12' max='64' value={length} onChange={e=>setLength(+e.target.value)} className='w-full'/></label><div className='mt-3 flex flex-wrap gap-4'><label className='flex gap-2'><input type='checkbox' checked={upper} onChange={e=>setUpper(e.target.checked)}/>Uppercase</label><label className='flex gap-2'><input type='checkbox' checked={digits} onChange={e=>setDigits(e.target.checked)}/>Numbers</label><label className='flex gap-2'><input type='checkbox' checked={symbols} onChange={e=>setSymbols(e.target.checked)}/>Symbols</label></div></div><div className='border-t pt-6'><div className='flex gap-2'><input readOnly value={phrase} className='min-w-0 flex-1 rounded border p-3 font-mono'/><button onClick={()=>navigator.clipboard.writeText(phrase)} className='rounded bg-slate-800 px-4 text-white'>Copy</button></div><label className='mt-4 block'>Words: {words}<input type='range' min='4' max='10' value={words} onChange={e=>setWords(+e.target.value)} className='w-full'/></label></div><button onClick={()=>setNonce(n=>n+1)} className='rounded bg-sky-600 px-5 py-2 text-white'>Generate new</button></section></LocalToolLayout>}
