import type { Tool } from '@/types/tool';

export const TOOLS: Tool[] = [
  ['image-compressor','Image Compressor','Reduce image file sizes locally.','Images',['image','compress','optimize','media']],
  ['regex-tester','Regex Tester & Explainer','Test regular expressions and understand their matches.','Developer',['text','developer','regex','code']],
  ['text-diff','Text Diff Checker','Compare two pieces of text and highlight differences.','Text & Data',['text','compare','diff']],
  ['color-converter','Color Code Converter','Convert HEX, RGB and HSL color values.','Converters',['color','design','developer','converter']],
  ['placeholder-generator','Placeholder Image Generator','Create custom placeholder images locally.','Images',['image','design','placeholder']],
  ['text-analyzer','Text Statistics / Analyzer','Count words, characters, sentences and more.','Text & Data',['text','stats','analyzer','counter']],
  ['image-metadata','Image Metadata Remover','View and remove EXIF metadata from JPEG images.','Privacy & Security',['image','privacy','exif','metadata','security']],
  ['markdown-editor','Markdown Editor','Edit Markdown with a live local preview.','Text & Data',['text','markdown','editor','writing']],
  ['csv-converter','CSV to JSON/XML Converter','Convert CSV data to JSON or XML locally.','Converters',['csv','json','xml','converter','data','developer']],
  ['contrast-checker','Text Contrast Checker','Check color contrast against accessibility guidance.','Accessibility',['accessibility','color','design','wcag']],
  ['image-resizer','Image Resizer','Resize images to specific dimensions locally.','Images',['image','resize','dimensions','optimize']],
  ['image-cropper','Image Cropper','Crop images locally in your browser.','Images',['image','crop','edit','dimensions']],
  ['lorem-ipsum-generator','Lorem Ipsum Generator','Generate placeholder text.','Generators',['text','generator','placeholder','design']],
  ['regex-generator','Easy Regex Generator','Build common regular expressions without memorizing syntax.','Developer',['regex','generator','developer','text','code']],
  ['find-replace','Find & Replace in Text','Find and replace text with optional regex support.','Text & Data',['text','find','replace','regex']],
  ['data-anonymizer','Data Anonymizer','Detect and redact common sensitive data locally.','Privacy & Security',['text','privacy','security','anonymize','redact']],
  ['css-specificity-calculator','CSS Specificity Calculator','Calculate and explain CSS selector specificity.','Developer',['css','developer','specificity','design']],
  ['unit-converter','Unit Converter','Convert common measurement units.','Converters',['converter','units','measurement','math']],
  ['http-status-codes','HTTP Status Code Explainer','Look up HTTP status codes and meanings.','Developer',['http','developer','reference','network']],
  ['list-cleaner','List Cleaner & Formatter','Sort, deduplicate and format text lists.','Text & Data',['text','list','format','cleaner','sort']],
  ['html-tag-explainer','HTML Tag Explainer','Reference standard HTML tags and their uses.','Developer',['html','developer','reference','code']],
  ['file-hash','File Hash & Checksum','Generate SHA-256, SHA-384 and SHA-512 checksums without uploading files.','Privacy & Security',['privacy','hash','checksum','file','security']],
  ['json-toolbox','JSON Toolbox','Format, minify, validate and sort JSON locally.','Developer',['json','format','validate','developer','data']],
  ['url-cleaner','Tracking URL Cleaner','Remove common tracking parameters and inspect URL parts locally.','Privacy & Security',['privacy','url','tracking','utm','cleaner']],
  ['password-generator','Password & Passphrase Generator','Generate cryptographically secure passwords and passphrases locally.','Privacy & Security',['password','security','privacy','generator']],
  ['encoder-decoder','Encoder / Decoder','Encode and decode Base64, URLs, HTML entities and Unicode text.','Developer',['base64','url','html','unicode','encode','decode']],
  ['jwt-inspector','JWT Inspector','Decode JWT headers and payloads locally without sending tokens anywhere.','Privacy & Security',['jwt','token','developer','privacy','security']],
  ['timestamp-tool','Timestamp & Date Toolkit','Convert Unix timestamps, ISO dates, UTC and local time.','Converters',['date','time','timestamp','unix','converter']],
  ['uuid-generator','UUID Generator','Generate and validate UUIDs locally.','Generators',['uuid','generator','developer','identifier']],
  ['browser-privacy','Browser Privacy Inspector','See what your browser exposes to websites without transmitting the results.','Privacy & Security',['privacy','browser','fingerprint','security']],
  ['text-privacy-cleaner','Text Privacy Cleaner','Reveal or remove hidden Unicode, control and zero-width characters.','Privacy & Security',['privacy','text','unicode','cleaner','security']],
  ['image-converter','Image Format Converter','Convert supported images to PNG, JPEG or WebP locally.','Images',['image','convert','png','jpeg','webp']],
].map(([slug,name,description,category,tags], index) => ({
  id: String(index + 1),
  slug: `/${slug}`,
  name,
  description,
  category,
  tags,
  processing: 'local',
  networkRequired: false,
  storesData: false,
})) as Tool[];

export const TOOL_BY_SLUG = new Map(TOOLS.map((tool) => [tool.slug, tool]));
export const TOOL_CATEGORIES = [...new Set(TOOLS.map((tool) => tool.category))];
