'use client';
import { useState } from 'react';
import LocalToolLayout from '@/components/LocalToolLayout';

type Algorithm = 'SHA-256' | 'SHA-384' | 'SHA-512'; type Encoding = 'hex' | 'base64';
const hex = (bytes: Uint8Array) => Array.from(bytes).map(value => value.toString(16).padStart(2,'0')).join('');
const base64 = (bytes: Uint8Array) => btoa(Array.from(bytes, value => String.fromCharCode(value)).join(''));
const fromHex = (value: string) => { if (!/^(?:[0-9a-f]{2})+$/i.test(value)) throw new Error('Expected an even-length hexadecimal value.'); return new Uint8Array(value.match(/../g)!.map(byte => parseInt(byte, 16))); };
const fromBase64 = (value: string) => Uint8Array.from(atob(value), char => char.charCodeAt(0));
async function importKey(secret: string, algorithm: Algorithm, usage: KeyUsage[]) { return crypto.subtle.importKey('raw', new TextEncoder().encode(secret), { name: 'HMAC', hash: algorithm }, false, usage); }
export default function HmacToolPage() {
  const [secret, setSecret] = useState('local-secret'); const [message, setMessage] = useState('ToolStack'); const [algorithm, setAlgorithm] = useState<Algorithm>('SHA-256'); const [encoding, setEncoding] = useState<Encoding>('hex'); const [output, setOutput] = useState(''); const [expected, setExpected] = useState(''); const [status, setStatus] = useState('');
  const generate = async () => { try { const key = await importKey(secret, algorithm, ['sign']); const signature = new Uint8Array(await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(message))); setOutput(encoding === 'hex' ? hex(signature) : base64(signature)); setStatus(''); } catch (err) { setStatus((err as Error).message); } };
  const verify = async () => { try { const key = await importKey(secret, algorithm, ['verify']); const bytes = encoding === 'hex' ? fromHex(expected.trim()) : fromBase64(expected.trim()); const valid = await crypto.subtle.verify('HMAC', key, bytes, new TextEncoder().encode(message)); setStatus(valid ? 'HMAC matches.' : 'HMAC does not match.'); } catch (err) { setStatus((err as Error).message); } };
  return <LocalToolLayout title='HMAC Generator & Verifier' description='Generate or verify HMAC-SHA signatures locally with Web Crypto. Secrets and messages stay in the browser.'><section className='mx-auto max-w-3xl rounded-xl bg-white p-6 shadow'><label className='font-semibold'>Secret<input type='password' value={secret} onChange={event => setSecret(event.target.value)} className='mt-2 w-full rounded border p-3 font-mono'/></label><label className='mt-4 block font-semibold'>Message<textarea value={message} onChange={event => setMessage(event.target.value)} className='mt-2 h-32 w-full rounded border p-3 font-mono'/></label><div className='mt-4 grid gap-3 sm:grid-cols-2'><select value={algorithm} onChange={event => setAlgorithm(event.target.value as Algorithm)} className='rounded border p-2'><option>SHA-256</option><option>SHA-384</option><option>SHA-512</option></select><select value={encoding} onChange={event => setEncoding(event.target.value as Encoding)} className='rounded border p-2'><option value='hex'>Hex</option><option value='base64'>Base64</option></select></div><button onClick={() => void generate()} className='mt-5 rounded bg-sky-600 px-4 py-2 text-white'>Generate HMAC</button>{output && <div className='mt-4 flex gap-2'><input readOnly value={output} className='min-w-0 flex-1 rounded border p-2 font-mono text-xs'/><button onClick={() => navigator.clipboard.writeText(output)} className='rounded bg-slate-800 px-3 text-white'>Copy</button></div>}<div className='mt-6 border-t pt-5'><label className='font-semibold'>Expected HMAC<input value={expected} onChange={event => setExpected(event.target.value)} className='mt-2 w-full rounded border p-2 font-mono text-xs'/></label><button disabled={!expected} onClick={() => void verify()} className='mt-3 rounded bg-emerald-600 px-4 py-2 text-white disabled:opacity-40'>Verify</button></div>{status && <p className={`mt-4 ${status === 'HMAC matches.' ? 'text-emerald-700' : 'text-amber-800'}`} aria-live='polite'>{status}</p>}</section></LocalToolLayout>;
}
