'use client';
import { useMemo, useState } from 'react';
import Papa from 'papaparse';
import LocalToolLayout from '@/components/LocalToolLayout';

const escapeXml=(value:unknown)=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
const xmlName=(name:string,index:number)=>{const cleaned=name.trim().replace(/[^A-Za-z0-9_.-]/g,'_').replace(/^[^A-Za-z_]+/,'');return cleaned||`field_${index+1}`};
function toXml(rows:Record<string,unknown>[]){const lines=['<?xml version="1.0" encoding="UTF-8"?>','<root>'];for(const row of rows){lines.push('  <item>');Object.entries(row).forEach(([key,value],i)=>{const tag=xmlName(key,i);lines.push(`    <${tag}>${escapeXml(value)}</${tag}>`)});lines.push('  </item>')}lines.push('</root>');return lines.join('\n')}
export default function CsvConverterPage(){const [csv,setCsv]=useState('Year,Make,Model\n1997,Ford,E350\n2000,Mercury,Cougar');const [tab,setTab]=useState<'json'|'xml'>('json');const parsed=useMemo(()=>Papa.parse<Record<string,unknown>>(csv,{header:true,skipEmptyLines:true}),[csv]);const json=useMemo(()=>JSON.stringify(parsed.data,null,2),[parsed.data]);const xml=useMemo(()=>toXml(parsed.data),[parsed.data]);const output=tab==='json'?json:xml;return <LocalToolLayout title='CSV to JSON/XML Converter' description='Convert CSV to structured JSON or well-formed XML locally. XML values are escaped and column names are normalized for valid element names.'><section className='mx-auto max-w-7xl rounded-xl bg-white p-6 shadow'><div className='mb-4 flex gap-2'><button onClick={()=>setTab('json')} className={`rounded px-4 py-2 ${tab==='json'?'bg-sky-600 text-white':'bg-slate-100'}`}>JSON</button><button onClick={()=>setTab('xml')} className={`rounded px-4 py-2 ${tab==='xml'?'bg-sky-600 text-white':'bg-slate-100'}`}>XML</button></div><div className='grid gap-4 md:grid-cols-2'><textarea value={csv} onChange={e=>setCsv(e.target.value)} className='h-96 rounded border p-4 font-mono'/><pre className='h-96 overflow-auto whitespace-pre-wrap rounded border bg-slate-50 p-4 font-mono text-sm'>{output}</pre></div>{parsed.errors.length>0&&<div className='mt-4 rounded border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900'>{parsed.errors.slice(0,5).map((e,i)=><div key={i}>Row {e.row??'?'}: {e.message}</div>)}</div>}<button onClick={()=>navigator.clipboard.writeText(output)} className='mt-4 rounded bg-slate-800 px-4 py-2 text-white'>Copy {tab.toUpperCase()}</button></section></LocalToolLayout>}
