'use client';
import { useMemo, useState } from 'react';
import LocalToolLayout from '@/components/LocalToolLayout';
import { diffJson } from '@/lib/json-diff';

function sortObject(value: unknown): unknown { if (Array.isArray(value)) return value.map(sortObject); if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a],[b]) => a.localeCompare(b)).map(([key, item]) => [key, sortObject(item)])); return value; }
type Mode = 'pretty' | 'minify' | 'sort' | 'diff';
export default function JsonToolboxPage() {
  const [input, setInput] = useState('{"name":"ToolStack","privacy":true,"count":41}'); const [compare, setCompare] = useState('{"name":"ToolStack","privacy":true,"count":42,"offline":true}'); const [mode, setMode] = useState<Mode>('pretty');
  const result = useMemo(() => { try { const parsed = JSON.parse(input); if (mode === 'diff') { const other = JSON.parse(compare); return { output: JSON.stringify(diffJson(parsed, other), null, 2), error: '' }; } return { output: mode === 'minify' ? JSON.stringify(parsed) : JSON.stringify(mode === 'sort' ? sortObject(parsed) : parsed, null, 2), error: '' }; } catch (err) { return { output: '', error: (err as Error).message }; } }, [input, compare, mode]);
  return <LocalToolLayout title='JSON Toolbox' description='Validate, format, minify, sort and structurally compare JSON entirely in your browser.'><section className='mx-auto max-w-6xl rounded-xl bg-white p-6 shadow'><div className='mb-4 flex flex-wrap gap-2'>{(['pretty','minify','sort','diff'] as Mode[]).map(value => <button key={value} onClick={() => setMode(value)} className={`rounded px-4 py-2 ${mode === value ? 'bg-sky-600 text-white' : 'bg-slate-100 text-slate-700'}`}>{value === 'pretty' ? 'Pretty print' : value === 'sort' ? 'Sort keys' : value === 'diff' ? 'Structural diff' : 'Minify'}</button>)}</div><div className={`grid gap-4 ${mode === 'diff' ? 'lg:grid-cols-3' : 'md:grid-cols-2'}`}><textarea aria-label='JSON input' value={input} onChange={event => setInput(event.target.value)} className='h-96 rounded border p-4 font-mono'/>{mode === 'diff' && <textarea aria-label='JSON comparison input' value={compare} onChange={event => setCompare(event.target.value)} className='h-96 rounded border p-4 font-mono'/>}<pre className='h-96 overflow-auto whitespace-pre-wrap rounded border bg-slate-50 p-4 font-mono text-sm'>{result.error ? `Invalid JSON: ${result.error}` : result.output}</pre></div>{!result.error && <button onClick={() => navigator.clipboard.writeText(result.output)} className='mt-4 rounded bg-slate-800 px-4 py-2 text-white'>Copy result</button>}</section></LocalToolLayout>;
}
